name: Data Request
description: Request new data or report broken data points
title: "[DATA REQUEST]: "
labels: ["data-request"]
assignees: 
  - juanpflores

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a data request! 
        Use the fields below for both new data requests and fixing broken data.
  
  - type: checkboxes
    id: request_type
    attributes:
      label: Request Type
      description: "Check the box that applies"
      options:
        - label: New Data Request
        - label: Fix Broken Data Points
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a clear description of the new data needed or the issue with existing data."
      placeholder: "Briefly describe the data request or issue..."
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose/Use Case
      description: "Explain how this data will be used or why it needs to be fixed."
      placeholder: "Describe the purpose or use case for this data..."
    validations:
      required: true

  - type: textarea
    id: goal_alignment
    attributes:
      label: Goal Alignment
      description: "Explain how this request or fix supports an EDU or GitHub goal or target."
      placeholder: "Describe how this request aligns with our goals..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: "Describe how this request or broken data issue affects your work or decision-making."
      placeholder: "Explain the impact of this data request or issue..."
    validations:
      required: true

  - type: textarea
    id: specific_data_points
    attributes:
      label: Specific Data Points
      description: "For new data: list the metrics or fields needed. For broken data: specify which metrics or fields are incorrect or missing."
      placeholder: "List the specific data points needed or affected..."
    validations:
      required: true

  - type: input
    id: data_format
    attributes:
      label: Data Formatting
      description: "For new data: desired format (Table, Graph, etc.). For broken data: current or expected format."
      placeholder: "Specify the desired or expected data format..."
    validations:
      required: true

  - type: input
    id: time_range
    attributes:
      label: Time Range
      description: "Specify the time period the data should cover or if it will be Dynamic (example: Last 30 days)."
    validations:
      required: true
      

  - type: input
    id: segmentation
    attributes:
      label: Segmentation
      description: "Indicate if data needs to be broken down by region, program, etc."

  - type: input
    id: data_location
    attributes:
      label: Data Location (If Applicable)
      description: "Where is the existing or broken data displayed or stored? (Dashboard URL, report name, etc.)"

  - type: textarea
    id: expected_correct_values
    attributes:
      label: Expected Correct Values (If Known)
      description: "Detail what the correct data should be, if known. Provide a few examples."

  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: "When do you need this data or fix by?"
      placeholder: "MM/DD/YYYY"
    validations:
      required: true

  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders
      description: "Who is interested in or impacted by this request or fix?"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add screenshots, links, or any extra details that might help."

  - type: markdown
    attributes:
      value: |
        Thank you for your request! We will review it and get back to you as soon as possible.
        If you have any questions, please feel free to reach out.